name: Code Coverage with reviewdog
description: Warns of lines of code not covered by the test.
branding:
  icon: code
  color: blue
inputs:
  fail_level:
    description: |
      Unless none, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the
      given level [info,warning,error]
    default: "none"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter]
    default: "added"
  github_token:
    description: "GITHUB_TOKEN"
    default: "${{ github.token }}"
    required: false
  lcov_path:
    description: Lcov files path. Support for glob pattern.
    required: true
  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-check,github-pr-review].
      Default is `github-pr-review`.
    default: "github-pr-review"
    required: false
  tool_name:
    description: "Tool name to use for reviewdog reporter"
    default: "code-coverage"
    required: false
  delete_previous_comments:
    description: "Delete previous comments made by the same tool."
    default: "true"
    required: false

runs:
  using: composite
  steps:
    - uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0
      with:
        reviewdog_version: latest
    - shell: bash
      run: |
        # Determine OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        
        case "$OS" in
          linux)
            case "$ARCH" in
              x86_64)
                BINARY="lcov_to_checkstyle-x86_64-unknown-linux-musl"
                ;;
              aarch64|arm64)
                BINARY="lcov_to_checkstyle-aarch64-unknown-linux-musl"
                ;;
              *)
                echo "Unsupported Linux architecture: $ARCH"
                exit 1
                ;;
            esac
            ;;
          darwin)
            BINARY="lcov_to_checkstyle-x86_64-apple-darwin"
            ;;
          *)
            echo "Unsupported OS: $OS"
            exit 1
            ;;
        esac
        
        echo "Downloading $BINARY for $OS/$ARCH"
        curl -L -o lcov_to_checkstyle "https://github.com/aki77/lcov_to_checkstyle/releases/download/v0.4.0/$BINARY"
        chmod +x lcov_to_checkstyle
    - name: Install lcov-util from crates.io
      uses: baptiste0928/cargo-install@b687c656bda5733207e629b50a22bf68974a0305
      with:
        crate: lcov-util
        version: "0.2.1"
    - uses: aki77/delete-pr-comments-action@410baf9bdfd6aa97206d7d723745ce2394e62513 # v3.1.0
      if: inputs.delete_previous_comments == 'true'
      with:
        bodyContains: "[${{ inputs.tool_name }}]"
        noReply: "true"
    - id: reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      run: |
        lcov-merge $(ls ${{ inputs.lcov_path }}) | \
          ./lcov_to_checkstyle | \
          reviewdog -f=checkstyle -name=${{ inputs.tool_name }} -reporter=${{ inputs.reporter }} \
            -fail-level=${{ inputs.fail_level }} -filter-mode=${{ inputs.filter_mode }}

      shell: bash
